server:
  port: 2801
spring:


  servlet:
    multipart:
      max-file-size: 10MB
      # 设置文件大小
      max-request-size: 100MB


  web:
    resources:
      static-locations: classpath:/resources/,classpath:/static/,file:${upload.fileUploadDic}
  thymeleaf:
    #    prefix: classpath:/static

    cache: false
    encoding: utf-8
    mode: HTML

  profiles:
    active: @activatedProperties@

# mybatis 配置
mybatis-plus:
  type-aliases-package: com.site.blog.entity
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: "tb_"

logging:
  level.com.site.blog: debug
  file:
    path: logs
#访问静态资源
upload:
  uploadAuthorImg: ${user.home}/.myblog/authorImg/
  fileUploadDic: ${user.home}/.myblog/upload/
  sqlAuthorImg: "/authorImg/"
  fileSqlDic: "/upload/"

